services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs_tutorial_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_tutorial
    ports:
      - '5432:5432'
    volumes:
      - nestjs_tutorial_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nestjs_tutorial_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - nestjs_tutorial_redisdata:/data

volumes:
  nestjs_tutorial_pgdata:
  nestjs_tutorial_redisdata:
